fix next start failures due to output: export setting
Fails with:

Error: "next start" does not work with "output: export" configuration. Use "npx serve@latest out" instead.

Signed-off-by: Jakub Sokołowski <jakub@status.im>